package com.yaorange.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-08-21T14:01:02.569+08:00
 * Generated source version: 3.2.13
 */
@WebService(targetNamespace = "http://webservice.yaorange.com/", name = "WSInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WSInterface {

    @WebMethod
    @RequestWrapper(localName = "getState", targetNamespace = "http://webservice.yaorange.com/", className = "com.yaorange.webservice.GetState")
    @ResponseWrapper(localName = "getStateResponse", targetNamespace = "http://webservice.yaorange.com/", className = "com.yaorange.webservice.GetStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getState(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0
    );
}
